// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjDmUNZEqvCLvZNmSwaDsmKCnBk7vBLZs',
    appId: '1:1066901926124:web:65729dfd9dbc19367e35c9',
    messagingSenderId: '1066901926124',
    projectId: 'whatsapp-clone-94eee',
    authDomain: 'whatsapp-clone-94eee.firebaseapp.com',
    storageBucket: 'whatsapp-clone-94eee.appspot.com',
    measurementId: 'G-R799TY3G02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWD90IqZNQ6xPSNY3albLRYXXiFb2UsmE',
    appId: '1:1066901926124:android:06ab84ca0ca64b3e7e35c9',
    messagingSenderId: '1066901926124',
    projectId: 'whatsapp-clone-94eee',
    storageBucket: 'whatsapp-clone-94eee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4sjfTaGDmUB2xoyYOGSugYL0nOLsxBI',
    appId: '1:1066901926124:ios:030ae0c0e4127d527e35c9',
    messagingSenderId: '1066901926124',
    projectId: 'whatsapp-clone-94eee',
    storageBucket: 'whatsapp-clone-94eee.appspot.com',
    androidClientId: '1066901926124-curnv2bmoeqie1ll23tgs5uig4dagl61.apps.googleusercontent.com',
    iosClientId: '1066901926124-f7fiv4e9j4jq5l696u33do7rqnr8gqfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4sjfTaGDmUB2xoyYOGSugYL0nOLsxBI',
    appId: '1:1066901926124:ios:a4436b8dd073b9bc7e35c9',
    messagingSenderId: '1066901926124',
    projectId: 'whatsapp-clone-94eee',
    storageBucket: 'whatsapp-clone-94eee.appspot.com',
    androidClientId: '1066901926124-curnv2bmoeqie1ll23tgs5uig4dagl61.apps.googleusercontent.com',
    iosClientId: '1066901926124-hhbq2bigmjcpriifc4707bgp02vacsc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
